### PR TITLE
add odpay 88x31

### PR DESCRIPTION
**Pull request by odpay**
I think you forgot this.

See https://github.com/DAMcraft/damcraft.de/pull/3

### CODE REVIEW

**Comment by odpay** [comment]
LGTM

**Comment by Nucceteere** [comment]
no

**Comment by Funtimes909** [comment]
sowwy >w< you're not gay enough >//w//<

**Comment by Nucceteere** [comment]
:skull:

**Comment by theoplegends** [comment]
merge NOW

**Comment by Nucceteere** [comment]
nuh uh

**Pull request closed without merging**
